apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nithishgwd/python-scrap:v1
        resources:
          limits:
            memory: "250Mi"
            cpu: "250m"
        ports:
        - containerPort: 8000 
        - containerPort: 8001


---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
    - name: webapp
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: metric
      protocol: TCP
      port: 8001
      targetPort: 8001
  type: LoadBalancer
  externalIPs: 
  
  
